spring:
  application:
    name: order-service

server:
  port: 9988
  undertow:
    port: 8001

camel:
  component:
    kafka:
      brokers: localhost:9092
  service:
    lra:
      enabled: true
      coordinator-url: http://localhost:50000
      local-participant-url: http://localhost:${server.undertow.port}/server
